INSERT INTO OrgaosEmissores VALUES ('ABNC'   , 'Academia Brasileira de Neurocirurgia'                                   , 1);
INSERT INTO OrgaosEmissores VALUES ('AGU'    , 'Advocacia-Geral da União'                                               , 1);
INSERT INTO OrgaosEmissores VALUES ('ANAC'   , 'Agência Nacional de Aviação Civil'                                      , 1);
INSERT INTO OrgaosEmissores VALUES ('CAER'   , 'Clube de Aeronáutica'                                                   , 1);
INSERT INTO OrgaosEmissores VALUES ('CAU'    , 'Conselho de Arquitetura e Urbanismo'                                    , 1);
INSERT INTO OrgaosEmissores VALUES ('CBM'    , 'Corpo de Bombeiro Militar'                                              , 2);
INSERT INTO OrgaosEmissores VALUES ('CFA'    , 'Conselho Federal Administração'                                         , 1);
INSERT INTO OrgaosEmissores VALUES ('CFB'    , 'Conselho Federal de Biblioteconomia'                                    , 1);
INSERT INTO OrgaosEmissores VALUES ('CFBIO'  , 'Conselho Federal de Biologia'                                           , 1);
INSERT INTO OrgaosEmissores VALUES ('CFBM'   , 'Conselho Federal de Biomedicina'                                        , 1);
INSERT INTO OrgaosEmissores VALUES ('CFC'    , 'Conselho Federal de Contabilidade'                                      , 1);
INSERT INTO OrgaosEmissores VALUES ('CFESS'  , 'Conselho Federal de Serviço Social'                                     , 1);
INSERT INTO OrgaosEmissores VALUES ('CFF'    , 'Conselho Regional de Farmácia'                                          , 2);
INSERT INTO OrgaosEmissores VALUES ('CFFA'   , 'Conselho Federal de Fonoaudiologia'                                     , 1);
INSERT INTO OrgaosEmissores VALUES ('CFM'    , 'Conselho Federal de Medicina'                                           , 1);
INSERT INTO OrgaosEmissores VALUES ('CFMV'   , 'Conselho Federal de Medicina Veterinária'                               , 1);
INSERT INTO OrgaosEmissores VALUES ('CFN'    , 'Conselho Federal de Nutrição'                                           , 1);
INSERT INTO OrgaosEmissores VALUES ('CFO'    , 'Conselho Federal de Odontologia'                                        , 1);
INSERT INTO OrgaosEmissores VALUES ('CFP'    , 'Conselho Federal de Psicologia'                                         , 1);
INSERT INTO OrgaosEmissores VALUES ('CFQ'    , 'Conselho Regional de Química'                                           , 2);
INSERT INTO OrgaosEmissores VALUES ('CFT'    , 'Conselho Federal dos Técnicos Industriais'                              , 1);
INSERT INTO OrgaosEmissores VALUES ('CFTA'   , 'Conselho Federal dos Técnicos Agrícolas'                                , 1);
INSERT INTO OrgaosEmissores VALUES ('CGPI'   , 'Coordenação Geral de Privilégios e Imunidades'                          , 1);
INSERT INTO OrgaosEmissores VALUES ('CGPMAF' , 'Coordenadoria Geral de Polícia Marítima, Aeronáutica e de Fronteiras'   , 1);
INSERT INTO OrgaosEmissores VALUES ('CIPC'   , 'Centro de Inteligência da Polícia Civil'                                , 1);
INSERT INTO OrgaosEmissores VALUES ('CNIG'   , 'Conselho Nacional de Imigração'                                         , 1);
INSERT INTO OrgaosEmissores VALUES ('CNT'    , 'Confederação Nacional do Transporte'                                    , 1);
INSERT INTO OrgaosEmissores VALUES ('CNTV'   , 'Confederação Nacional de Vigilantes & Prestadores de Serviços'          , 1);
INSERT INTO OrgaosEmissores VALUES ('COFECI' , 'Conselho Federal de Corretores de Imóveis'                              , 1);
INSERT INTO OrgaosEmissores VALUES ('COFECON', 'Conselho Federal de Economia'                                           , 1);
INSERT INTO OrgaosEmissores VALUES ('COFEM'  , 'Conselho Federal de Museologia'                                         , 1);
INSERT INTO OrgaosEmissores VALUES ('COFEN'  , 'Conselho Federal de Enfermagem'                                         , 1);
INSERT INTO OrgaosEmissores VALUES ('COFFITO', 'Conselho Regional de Fisioterapia e Terapia Ocupacional'                , 2);
INSERT INTO OrgaosEmissores VALUES ('COMAER' , 'Comando da Aeronáutica'                                                 , 1);
INSERT INTO OrgaosEmissores VALUES ('CONFE'  , 'Conselho Federal de Estatística'                                        , 1);
INSERT INTO OrgaosEmissores VALUES ('CONFEA' , 'Conselho Federal de Engenharia e Agronomia'                             , 1);
INSERT INTO OrgaosEmissores VALUES ('CONFEF' , 'Conselho Federal de Educação Física'                                    , 1);
INSERT INTO OrgaosEmissores VALUES ('CONFERE', 'Conselho Federal dos Representantes Comerciais'                         , 1);
INSERT INTO OrgaosEmissores VALUES ('CONRE'  , 'Conselho Regional de Estatística'                                       , 2);
INSERT INTO OrgaosEmissores VALUES ('CONRERP', 'Conselho Federal de Profissionais de Relações Públicas'                 , 1);
INSERT INTO OrgaosEmissores VALUES ('CORE'   , 'Conselho Regional dos Representantes Comerciais'                        , 2);
INSERT INTO OrgaosEmissores VALUES ('CORECON', 'Conselho Regional de Economia'                                          , 2);
INSERT INTO OrgaosEmissores VALUES ('COREM'  , 'Conselho Regional de Museologia'                                        , 2);
INSERT INTO OrgaosEmissores VALUES ('COREN'  , 'Conselho Regional de Enfermagem'                                        , 2);
INSERT INTO OrgaosEmissores VALUES ('CRA'    , 'Conselho Regional de Administração'                                     , 2);
INSERT INTO OrgaosEmissores VALUES ('CRAS'   , 'Centro de Referência de Assistência Social'                             , 1);
INSERT INTO OrgaosEmissores VALUES ('CRB'    , 'Conselho Regional de Biblioteconomia'                                   , 2);
INSERT INTO OrgaosEmissores VALUES ('CRBIO'  , 'Conselho Regional de Biologia'                                          , 2);
INSERT INTO OrgaosEmissores VALUES ('CRBM'   , 'Conselho Regional de Biomedicina'                                       , 2);
INSERT INTO OrgaosEmissores VALUES ('CRC'    , 'Conselho Regional de Contabilidade'                                     , 2);
INSERT INTO OrgaosEmissores VALUES ('CREA'   , 'Conselho Regional de Engenharia e Agronomia'                            , 2);
INSERT INTO OrgaosEmissores VALUES ('CRECI'  , 'Conselho Regional de Corretores de Imóveis'                             , 2);
INSERT INTO OrgaosEmissores VALUES ('CREF'   , 'Conselho Regional de Educação Física'                                   , 2);
INSERT INTO OrgaosEmissores VALUES ('CREFITO', 'Conselho Regional de Fisioterapia e Terapia Ocupacional'                , 2);
INSERT INTO OrgaosEmissores VALUES ('CRESS'  , 'Conselho Regional de Serviço Social'                                    , 2);
INSERT INTO OrgaosEmissores VALUES ('CRF'    , 'Conselho Regional de Farmácia'                                          , 2);
INSERT INTO OrgaosEmissores VALUES ('CRFA'   , 'Conselho Regional de Fonoaudiologia'                                    , 2);
INSERT INTO OrgaosEmissores VALUES ('CRM'    , 'Conselho Regional de Medicina'                                          , 2);
INSERT INTO OrgaosEmissores VALUES ('CRMV'   , 'Conselho Regional de Medicina Veterinária'                              , 2);
INSERT INTO OrgaosEmissores VALUES ('CRN'    , 'Conselho Regional de Nutrição'                                          , 2);
INSERT INTO OrgaosEmissores VALUES ('CRO'    , 'Conselho Regional de Odontologia'                                       , 2);
INSERT INTO OrgaosEmissores VALUES ('CRP'    , 'Conselho Regional de Psicologia'                                        , 2);
INSERT INTO OrgaosEmissores VALUES ('CRPRE'  , 'Conselho Regional de Profissionais de Relações Públicas'                , 2);
INSERT INTO OrgaosEmissores VALUES ('CRQ'    , 'Conselho Regional de Química'                                           , 2);
INSERT INTO OrgaosEmissores VALUES ('CRT'    , 'Conselho Regional dos Técnicos Industriais'                             , 2);
INSERT INTO OrgaosEmissores VALUES ('CRTA'   , 'Conselho Regional de Técnicos de Administração'                         , 2);
INSERT INTO OrgaosEmissores VALUES ('CTPS'   , 'Carteira de Trabalho e Previdência Social'                              , 2);
INSERT INTO OrgaosEmissores VALUES ('CV'     , 'Cartório Civil'                                                         , 3);
INSERT INTO OrgaosEmissores VALUES ('DELEMIG', 'Delegacia de Polícia de Imigração'                                      , 2);
INSERT INTO OrgaosEmissores VALUES ('DETRAN' , 'Departamento Estadual de Trânsito'                                      , 2);
INSERT INTO OrgaosEmissores VALUES ('DGPC'   , 'Diretoria Geral da Polícia Civil'                                       , 2);
INSERT INTO OrgaosEmissores VALUES ('DIC'    , 'Diretoria de Identificação Civil'                                       , 2);
INSERT INTO OrgaosEmissores VALUES ('DICC'   , 'Diretoria de Identificação Civil e Criminal'                            , 2);
INSERT INTO OrgaosEmissores VALUES ('DIREX'  , 'Diretoria Executiva'                                                    , 1);
INSERT INTO OrgaosEmissores VALUES ('DPF'    , 'Departamento de Polícia Federal'                                        , 1);
INSERT INTO OrgaosEmissores VALUES ('DPMAF'  , 'Divisão de Polícia Marítima, Aérea e de Fronteiras'                     , 1);
INSERT INTO OrgaosEmissores VALUES ('DPT'    , 'Departamento de Polícia Técnica Geral'                                  , 1);
INSERT INTO OrgaosEmissores VALUES ('DPTC'   , 'Departamento de Polícia Técnico Científica'                             , 1);
INSERT INTO OrgaosEmissores VALUES ('DREX'   , 'Delegacia Regional Executiva'                                           , 2);
INSERT INTO OrgaosEmissores VALUES ('DRT'    , 'Delegacia Regional do Trabalho'                                         , 2);
INSERT INTO OrgaosEmissores VALUES ('EB'     , 'Exército Brasileiro'                                                    , 1);
INSERT INTO OrgaosEmissores VALUES ('FAB'    , 'Força Aérea Brasileira'                                                 , 1);
INSERT INTO OrgaosEmissores VALUES ('FENAJ'  , 'Federação Nacional dos Jornalistas'                                     , 1);
INSERT INTO OrgaosEmissores VALUES ('FGTS'   , 'Fundo de Garantia do Tempo de Serviço'                                  , 1);
INSERT INTO OrgaosEmissores VALUES ('FIPE'   , 'Fundação Instituto de Pesquisas Econômicas'                             , 1);
INSERT INTO OrgaosEmissores VALUES ('FLS'    , 'Fundação Lyndolpho Silva'                                               , 1);
INSERT INTO OrgaosEmissores VALUES ('FUNAI'  , 'Fundação Nacional do Índio'                                             , 1);
INSERT INTO OrgaosEmissores VALUES ('GEJSP'  , 'Gerência de Estado de Justiça, Segurança Pública e Cidadania'           , 1);
INSERT INTO OrgaosEmissores VALUES ('GEJSPC' , 'Gerência de Estado de Justiça, Segurança Pública e Cidadania'           , 1);
INSERT INTO OrgaosEmissores VALUES ('GEJUSPC', 'Gerência de Estado de Justiça, Segurança Pública e Cidadania'           , 1);
INSERT INTO OrgaosEmissores VALUES ('GESP'   , 'Gerência de Estado de Segurança Pública'                                , 1);
INSERT INTO OrgaosEmissores VALUES ('GOVGO'  , 'Governo do Estado de Goiás'                                             , 1);
INSERT INTO OrgaosEmissores VALUES ('I CLA'  , 'Carteira de Identidade Classista'                                       , 1);
INSERT INTO OrgaosEmissores VALUES ('ICP'    , 'Instituto de Polícia Científica'                                        , 1);
INSERT INTO OrgaosEmissores VALUES ('IDAMP'  , 'Instituto de Identificação Dr. Aroldo Mendes Paiva'                     , 1);
INSERT INTO OrgaosEmissores VALUES ('IFP'    , 'Instituto Félix Pacheco'                                                , 1);
INSERT INTO OrgaosEmissores VALUES ('IGP'    , 'Instituto Geral de Perícias'                                            , 1);
INSERT INTO OrgaosEmissores VALUES ('IIACM'  , 'Instituto de Identificação Aderson Conceição de Melo'                   , 1);
INSERT INTO OrgaosEmissores VALUES ('IICC'   , 'Instituto de Identificação Civil e Criminal'                            , 1);
INSERT INTO OrgaosEmissores VALUES ('IICCECF', 'Instituto de Identificação Civil e Criminal Engrácia da Costa Francisco', 1);
INSERT INTO OrgaosEmissores VALUES ('IICM'   , 'Instituto de Identificação Carlos Menezes'                              , 1);
INSERT INTO OrgaosEmissores VALUES ('IIGP'   , 'Instituto de Identificação Gonçalo Pereira'                             , 1);
INSERT INTO OrgaosEmissores VALUES ('IIJDM'  , 'Instituto de Identificação João de Deus Martins'                        , 1);
INSERT INTO OrgaosEmissores VALUES ('IIRGD'  , 'Instituto de Identificação Ricardo Gumbleton Daunt'                     , 1);
INSERT INTO OrgaosEmissores VALUES ('IIPC'   , 'Instituto de Identificação da Polícia Civil'                            , 1);
INSERT INTO OrgaosEmissores VALUES ('IIPM'   , 'Instituto de Identificação Pedro Mello'                                 , 1);
INSERT INTO OrgaosEmissores VALUES ('IIRHM'  , 'Instituto de Identificação Raimundo Hermínio de Melo'                   , 1);
INSERT INTO OrgaosEmissores VALUES ('IITB'   , 'Instituto de Identificação Tavares Buril'                               , 1);
INSERT INTO OrgaosEmissores VALUES ('IML'    , 'Instituto Médico-Legal'                                                 , 1);
INSERT INTO OrgaosEmissores VALUES ('INI'    , 'Instituto Nacional de Identificação'                                    , 1);
INSERT INTO OrgaosEmissores VALUES ('IPF'    , 'Instituto Pereira Faustino'                                             , 1);
INSERT INTO OrgaosEmissores VALUES ('ITCP'   , 'Instituto Técnico-Científico de Perícia'                                , 1);
INSERT INTO OrgaosEmissores VALUES ('ITEP'   , 'Instituto Técnico-Científico de Perícia'                                , 1);
INSERT INTO OrgaosEmissores VALUES ('MAER'   , 'Ministério da Aeronáutica'                                              , 1);
INSERT INTO OrgaosEmissores VALUES ('MB'     , 'Marinha do Brasil'                                                      , 1);
INSERT INTO OrgaosEmissores VALUES ('MD'     , 'Ministério da Defesa'                                                   , 1);
INSERT INTO OrgaosEmissores VALUES ('MDS'    , 'Ministério da Cidadania'                                                , 1);
INSERT INTO OrgaosEmissores VALUES ('MEC'    , 'Ministério da Educação e Cultura'                                       , 1);
INSERT INTO OrgaosEmissores VALUES ('MEX'    , 'Ministério do Exército'                                                 , 1);
INSERT INTO OrgaosEmissores VALUES ('MINDEF' , 'Ministério da Defesa'                                                   , 1);
INSERT INTO OrgaosEmissores VALUES ('MJ'     , 'Ministério da Justiça'                                                  , 1);
INSERT INTO OrgaosEmissores VALUES ('MM'     , 'Ministério da Marinha'                                                  , 1);
INSERT INTO OrgaosEmissores VALUES ('MMA'    , 'Ministério da Marinha'                                                  , 1);
INSERT INTO OrgaosEmissores VALUES ('MP'     , 'Ministério Público'                                                     , 1);
INSERT INTO OrgaosEmissores VALUES ('MPAS'   , 'Ministério da Previdência e Assistência Social'                         , 1);
INSERT INTO OrgaosEmissores VALUES ('MPE'    , 'Ministério Público Estadual'                                            , 1);
INSERT INTO OrgaosEmissores VALUES ('MPF'    , 'Ministério Público Federal'                                             , 1);
INSERT INTO OrgaosEmissores VALUES ('MPT'    , 'Ministério Público do Trabalho'                                         , 1);
INSERT INTO OrgaosEmissores VALUES ('MRE'    , 'Ministério das Relações Exteriores'                                     , 1);
INSERT INTO OrgaosEmissores VALUES ('MT'     , 'Ministério do Trabalho'                                                 , 1);
INSERT INTO OrgaosEmissores VALUES ('MTE'    , 'Ministério da Economia'                                                 , 1);
INSERT INTO OrgaosEmissores VALUES ('MTPS'   , 'Ministério do Trabalho e Previdência Social'                            , 1);
INSERT INTO OrgaosEmissores VALUES ('NUMIG'  , 'Núcleo de Polícia de Imigração'                                         , 2);
INSERT INTO OrgaosEmissores VALUES ('OAB'    , 'Ordem dos Advogados do Brasil'                                          , 1);
INSERT INTO OrgaosEmissores VALUES ('OMB'    , 'Ordens dos Músicos do Brasil'                                           , 1);
INSERT INTO OrgaosEmissores VALUES ('PC'     , 'Polícia Civil'                                                          , 2);
INSERT INTO OrgaosEmissores VALUES ('PF'     , 'Polícia Federal'                                                        , 1);
INSERT INTO OrgaosEmissores VALUES ('PGFN'   , 'Procuradoria Geral da Fazenda Nacional'                                 , 1);
INSERT INTO OrgaosEmissores VALUES ('PM'     , 'Polícia Militar'                                                        , 2);
INSERT INTO OrgaosEmissores VALUES ('POLITEC', 'Perícia Oficial e Identificação Técnica'                                , 1);
INSERT INTO OrgaosEmissores VALUES ('PRF'    , 'Polícia Rodoviária Federal'                                             , 1);
INSERT INTO OrgaosEmissores VALUES ('PTC'    , 'Polícia Tecnico-Científica'                                             , 1);
INSERT INTO OrgaosEmissores VALUES ('SCC'    , 'Secretaria de Estado da Casa Civil'                                     , 2);
INSERT INTO OrgaosEmissores VALUES ('SCJDS'  , 'Secretaria Coordenadora de Justiça e Defesa Social'                     , 2);
INSERT INTO OrgaosEmissores VALUES ('SDS'    , 'Secretaria de Defesa Social'                                            , 2);
INSERT INTO OrgaosEmissores VALUES ('SECC'   , 'Secretaria de Estado da Casa Civil'                                     , 2);
INSERT INTO OrgaosEmissores VALUES ('SECCDE' , 'Secretaria de Estado da Casa Civil e Desenvolvimento Econômico'         , 2);
INSERT INTO OrgaosEmissores VALUES ('SEDS'   , 'Secretaria de Estado da Defesa Social'                                  , 2);
INSERT INTO OrgaosEmissores VALUES ('SEGUP'  , 'Secretaria de Estado da Segurança Pública e da Defesa Social'           , 2);
INSERT INTO OrgaosEmissores VALUES ('SEJSP'  , 'Secretaria de Estado de Justiça e Segurança Pública'                    , 2);
INSERT INTO OrgaosEmissores VALUES ('SEJUC'  , 'Secretaria de Estado da Justica'                                        , 2);
INSERT INTO OrgaosEmissores VALUES ('SEJUSP' , 'Secretaria de Estado de Justiça e Segurança Pública'                    , 2);
INSERT INTO OrgaosEmissores VALUES ('SEPC'   , 'Secretaria de Estado da Polícia Civil'                                  , 2);
INSERT INTO OrgaosEmissores VALUES ('SES'    , 'Secretaria de Estado da Segurança'                                      , 2);
INSERT INTO OrgaosEmissores VALUES ('SESC'   , 'Secretaria de Estado da Segurança e Cidadania'                          , 2);
INSERT INTO OrgaosEmissores VALUES ('SESDC'  , 'Secretaria de Estado da Segurança, Defesa e Cidadania'                  , 2);
INSERT INTO OrgaosEmissores VALUES ('SESDEC' , 'Secretaria de Estado da Segurança, Defesa e Cidadania'                  , 2);
INSERT INTO OrgaosEmissores VALUES ('SESEG'  , 'Secretaria Estadual de Segurança'                                       , 2);
INSERT INTO OrgaosEmissores VALUES ('SESP'   , 'Secretaria de Estado da Segurança Pública'                              , 2);
INSERT INTO OrgaosEmissores VALUES ('SESPAP' , 'Secretaria de Estado da Segurança Pública e Administração Penitenciária', 2);
INSERT INTO OrgaosEmissores VALUES ('SESPDC' , 'Secretaria de Estado de Segurança Publica e Defesa do Cidadão'          , 2);
INSERT INTO OrgaosEmissores VALUES ('SESPDS' , 'Secretaria de Estado de Segurança Pública e Defesa Social'              , 2);
INSERT INTO OrgaosEmissores VALUES ('SGPC'   , 'Superintendência Geral de Polícia Civil'                                , 1);
INSERT INTO OrgaosEmissores VALUES ('SGPJ'   , 'Superintendência Geral de Polícia Judiciária'                           , 1);
INSERT INTO OrgaosEmissores VALUES ('SIM'    , 'Serviço de Identificação da Marinha'                                    , 1);
INSERT INTO OrgaosEmissores VALUES ('SJ'     , 'Secretaria da Justiça'                                                  , 2);
INSERT INTO OrgaosEmissores VALUES ('SJCDH'  , 'Secretaria da Justiça e dos Direitos Humanos'                           , 2);
INSERT INTO OrgaosEmissores VALUES ('SJDS'   , 'Secretaria Coordenadora de Justiça e Defesa Social'                     , 2);
INSERT INTO OrgaosEmissores VALUES ('SJS'    , 'Secretaria da Justiça e Segurança'                                      , 2);
INSERT INTO OrgaosEmissores VALUES ('SJTC'   , 'Secretaria da Justiça do Trabalho e Cidadania'                          , 2);
INSERT INTO OrgaosEmissores VALUES ('SJTS'   , 'Secretaria da Justiça do Trabalho e Segurança'                          , 2);
INSERT INTO OrgaosEmissores VALUES ('SNJ'    , 'Secretaria Nacional de Justiça / Departamento de Estrangeiros'          , 2);
INSERT INTO OrgaosEmissores VALUES ('SPMAF'  , 'Serviço de Polícia Marítima, Aérea e de Fronteiras'                     , 2);
INSERT INTO OrgaosEmissores VALUES ('SPTC'   , 'Secretaria de Polícia Técnico-Científica'                               , 2);
INSERT INTO OrgaosEmissores VALUES ('SRDPF'  , 'Superintendência Regional do Departamento de Polícia Federal'           , 2);
INSERT INTO OrgaosEmissores VALUES ('SRF'    , 'Receita Federal'                                                        , 1);
INSERT INTO OrgaosEmissores VALUES ('SRTE'   , 'Superintendência Regional do Trabalho'                                  , 2);
INSERT INTO OrgaosEmissores VALUES ('SSDC'   , 'Secretaria da Segurança, Defesa e Cidadania'                            , 2);
INSERT INTO OrgaosEmissores VALUES ('SSDS'   , 'Secretaria da Segurança e da Defesa Social'                             , 2);
INSERT INTO OrgaosEmissores VALUES ('SSI'    , 'Secretaria de Segurança e Informações'                                  , 2);
INSERT INTO OrgaosEmissores VALUES ('SSP'    , 'Secretaria de Segurança Pública'                                        , 2);
INSERT INTO OrgaosEmissores VALUES ('SSPCGP' , 'Secretaria de Segurança Pública e Coordenadoria Geral de Perícias'      , 2);
INSERT INTO OrgaosEmissores VALUES ('SSPDC'  , 'Secretaria de Segurança Pública e Defesa do Cidadão'                    , 2);
INSERT INTO OrgaosEmissores VALUES ('SSPDS'  , 'Secretaria de Segurança Pública e Defesa Social'                        , 2);
INSERT INTO OrgaosEmissores VALUES ('SSPPC'  , 'Secretaria de Segurança Pública Polícia Civil'                          , 2);
INSERT INTO OrgaosEmissores VALUES ('SUSEP'  , 'Superintendência de Seguros Privados'                                   , 1);
INSERT INTO OrgaosEmissores VALUES ('SUSEPE' , 'Superintendência dos Serviços Penitenciários'                           , 2);
INSERT INTO OrgaosEmissores VALUES ('TJ'     , 'Tribunal de Justiça'                                                    , 1);
INSERT INTO OrgaosEmissores VALUES ('TJAEM'  , 'Tribunal Arbitral e Mediação dos Estados Brasileiros'                   , 1);
INSERT INTO OrgaosEmissores VALUES ('TRE'    , 'Tribunal Regional Eleitoral'                                            , 2);
INSERT INTO OrgaosEmissores VALUES ('TRF'    , 'Tribunal Regional Federal'                                              , 2);
INSERT INTO OrgaosEmissores VALUES ('TSE'    , 'Tribunal Superior Eleitoral'                                            , 1);
INSERT INTO OrgaosEmissores VALUES ('XXX'    , 'Orgão Estrangeiro'                                                      , 4);
INSERT INTO OrgaosEmissores VALUES ('ZZZ'    , 'Outro'                                                                  , 4);